replicaCount: 1

image:
  repository: akyldocker25/flask-app
  tag: "1751164444"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: null

env:
  DATABASE_URL: "postgresql://postgres:example@postgres:5432/postgres"

