replicaCount: 1

image:
  repository: akyldocker25/flask-app
  tag: flask-app:1751076386
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: null

env:
  DATABASE_URL: "postgresql://postgres:example@postgres:5432/postgres"

