name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code with PAT token
        uses: actions/checkout@v3
        with:
          persist-credentials: false # disable default GITHUB_TOKEN
          token: ${{ secrets.PAT_TOKEN }} # use your Personal Access Token here

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=flask-app:$(date +%s)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_TAG
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Update Helm values.yaml with new image tag
        run: |
          sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" flask-chart/values.yaml

      - name: Commit updated Helm chart and push
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          git config user.name "akylgit"
          git config user.email "johns.ak87@gmail.com"
          git add flask-chart/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push origin HEAD:main
